name: 'Action CI'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run all

  # run unity tests & analyze result
  analyze:
    name: 'Publish Action'
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        if: ${{ always() }}
        with:
          checkName: 'Test Results'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkFailedStatus: neutral
